### ISSUE TITLE
bogon:nodeclub x$ make build

### ISSUE THREAD

**Issue by 95zz** [cnodejs/nodeclub#1054]
**bogon:~ x$ cd Desktop/work/jxtpro/nodeclub**
**bogon:nodeclub x$ make build**
Scaned. 3 asset(s) will be build.
Building... /public/editor.min.js
	processing... /public/libs/editor/editor.js ..build .. use 1414ms.
	processing... /public/libs/webuploader/webuploader.withoutimage.js ..build .. use 358ms.
	processing... /public/libs/editor/ext.js ..build .. use 37ms.
✔ Done. Build time 1816 ms.
Building... /public/stylesheets/index.min.css
	processing... /public/libs/bootstrap/css/bootstrap.css ..build .. use 330ms.
	processing... /public/stylesheets/common.css ..build .. use 48ms.
	processing... /public/stylesheets/style.less ..build .. use 102ms.
	processing... /public/stylesheets/responsive.css ..build .. use 10ms.
	processing... /public/stylesheets/jquery.atwho.css ..build .. use 3ms.
	processing... /public/libs/editor/editor.css ..build .. use 53ms.
	processing... /public/libs/webuploader/webuploader.css ..build .. use 13ms.
	processing... /public/libs/code-prettify/prettify.css ..build .. use 6ms.
	processing... /public/libs/font-awesome/css/font-awesome.css ..build .. use 48ms.
✔ Done. Build time 617 ms.
Building... /public/index.min.js
	processing... /public/libs/jquery-2.1.0.js ..build .. use 716ms.
	processing... /public/libs/lodash.compat.js ..build .. use 402ms.
	processing... /public/libs/jquery-ujs.js ..build .. use 43ms.
	processing... /public/libs/bootstrap/js/bootstrap.js ..build .. use 161ms.
	processing... /public/libs/jquery.caret.js ..build .. use 32ms.
	processing... /public/libs/jquery.atwho.js ..build .. use 84ms.
	processing... /public/libs/markdownit.js ..build .. use 442ms.
	processing... /public/libs/code-prettify/prettify.js ..build .. use 105ms.
	processing... /public/libs/qrcode.js ..build .. use 157ms.
	processing... /public/javascripts/main.js ..build .. use 18ms.
	processing... /public/javascripts/responsive.js ..build .. use 12ms.
✔ Done. Build time 2207 ms.
 🏁  Compile static assets done. Build time 4736 ms.
**assets.json is here:  /Users/x/Desktop/work/jxtpro/nodeclub/assets.json
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^**

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1132:14)
    at Object.<anonymous> (/Users/x/Desktop/work/jxtpro/nodeclub/node_modules/loader-builder/bin/builder:45:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

make: *** [build] Error 1
make: *** [build] Error 1
**bogon:nodeclub x$ node -v**
v10.6.0
**bogon:nodeclub x$ npm -v**
6.2.0

**Comment by 95zz** [comment]
更新了它就好了 ==> "loader-builder": "2.6.1",
