### ISSUE TITLE
项目跑不起来，报错如下

### ISSUE THREAD

**Issue by fengyurensheng** [cnodejs/nodeclub#1083]
/usr/local/nodeclub/app.js:56
    throw e;
    ^

[Error: Cannot find module './assets.json'
Require stack:
- /usr/local/nodeclub/app.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
  at Function.Module._load (internal/modules/cjs/loader.js:527:27)
  at Module.require (internal/modules/cjs/loader.js:683:19)
  at require (internal/modules/cjs/helpers.js:16:16)
  at Object.<anonymous> (/usr/local/nodeclub/app.js:53:14)
  at Module._compile (internal/modules/cjs/loader.js:777:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
  at Module.load (internal/modules/cjs/loader.js:643:32)
  at Function.Module._load (internal/modules/cjs/loader.js:556:12)
  at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
  at internal/main/run_main_module.js:17:11
] {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/nodeclub/app.js' ]
}

**Comment by yplonggit** [comment]
make
 build

**Comment by fengyurensheng** [comment]
现在项目跑起来了，但是注册激活邮件发送不了。昨天都可以发送，今天就发送不了。唯一做过的操作就是更改了项目的端口，这个应该是没有影响的。不知道是什么问题？怎么可以解决呢？




------------------ 原始邮件 ------------------
发件人: "yplonggit"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 下午2:55
收件人: "cnodejs/nodeclub"<nodeclub@noreply.github.com>;
抄送: "一飞冲天"<3538642127@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cnodejs/nodeclub] 项目跑不起来，报错如下 (#1083)




make
 build
