### ISSUE TITLE
关闭debug后，运行make build

### ISSUE THREAD

**Issue by qingfengfenga** [cnodejs/nodeclub#1105]
```
$ make build
Scaned. 3 asset(s) will be build.
Building... /public/editor.min.js
	processing... /public/libs/editor/editor.js ..build .. use 2496ms.
	processing... /public/libs/webuploader/webuploader.withoutimage.js ..build .. use 539ms.
	processing... /public/libs/editor/ext.js ..build .. use 72ms.
✔ Done. Build time 3115 ms.
Building... /public/stylesheets/index.min.css
	processing... /public/libs/bootstrap/css/bootstrap.css ..build .. use 416ms.
	processing... /public/stylesheets/common.css ..build .. use 74ms.
	processing... /public/stylesheets/style.less ..build .. use 139ms.
	processing... /public/stylesheets/responsive.css ..build .. use 22ms.
	processing... /public/stylesheets/jquery.atwho.css ..build .. use 7ms.
	processing... /public/libs/editor/editor.css ..build .. use 47ms.
	processing... /public/libs/webuploader/webuploader.css ..build .. use 2ms.
	processing... /public/libs/code-prettify/prettify.css ..build .. use 3ms.
	processing... /public/libs/font-awesome/css/font-awesome.css ..build .. use 82ms.
✔ Done. Build time 794 ms.
Building... /public/index.min.js
	processing... /public/libs/jquery-2.1.0.js ..build .. use 1374ms.
	processing... /public/libs/lodash.compat.js ..build .. use 546ms.
	processing... /public/libs/jquery-ujs.js ..build .. use 44ms.
	processing... /public/libs/bootstrap/js/bootstrap.js ..build .. use 248ms.
	processing... /public/libs/jquery.caret.js ..build .. use 54ms.
	processing... /public/libs/jquery.atwho.js ..build .. use 100ms.
	processing... /public/libs/markdownit.js ..build .. use 733ms.
	processing... /public/libs/code-prettify/prettify.js ..build .. use 144ms.
	processing... /public/libs/qrcode.js ..build .. use 404ms.
	processing... /public/javascripts/main.js ..build .. use 8ms.
	processing... /public/javascripts/responsive.js ..build .. use 20ms.
✔ Done. Build time 3690 ms.
 🏁  Compile static assets done. Build time 7607 ms.
assets.json is here:  /mnt/bbs/nodeclub/assets.json
fs.js:142
  throw new ERR_INVALID_CALLBACK(cb);
  ^

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at Object.<anonymous> (/mnt/bbs/nodeclub/node_modules/loader-builder/bin/builder:45:4)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

make: *** [build] 错误 1

```

**Comment by qingfengfenga** [comment]
已解决
更新这个包即可
一定要这个版本
loader-builder@2.6.1
2.7会报错

```
$ npm install  --save  loader-builder@2.6.1
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN ws@7.2.5 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.5 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ loader-builder@2.6.1
added 1 package from 1 contributor, removed 27 packages, updated 2 packages and audited 4960 packages in 18.476s
found 80 vulnerabilities (32 low, 19 moderate, 28 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[wyp@izuf67add25vlwipsj40w2z nodeclub]$ npm ls loader-builder
nodeclub@2.1.1 /mnt/bbs/nodeclub
└── loader-builder@2.6.1 

$ make build
Scaned. 3 asset(s) will be build.
Building... /public/editor.min.js
	processing... /public/libs/editor/editor.js ..build .. use 3624ms.
	processing... /public/libs/webuploader/webuploader.withoutimage.js ..build .. use 1407ms.
	processing... /public/libs/editor/ext.js ..build .. use 48ms.
✔ Done. Build time 5087 ms.
Building... /public/stylesheets/index.min.css
	processing... /public/libs/bootstrap/css/bootstrap.css ..build .. use 557ms.
	processing... /public/stylesheets/common.css ..build .. use 6ms.
	processing... /public/stylesheets/style.less ..build .. use 107ms.
	processing... /public/stylesheets/responsive.css ..build .. use 37ms.
	processing... /public/stylesheets/jquery.atwho.css ..build .. use 3ms.
	processing... /public/libs/editor/editor.css ..build .. use 45ms.
	processing... /public/libs/webuploader/webuploader.css ..build .. use 2ms.
	processing... /public/libs/code-prettify/prettify.css ..build .. use 13ms.
	processing... /public/libs/font-awesome/css/font-awesome.css ..build .. use 72ms.
✔ Done. Build time 845 ms.
Building... /public/index.min.js
	processing... /public/libs/jquery-2.1.0.js ..build .. use 2152ms.
	processing... /public/libs/lodash.compat.js ..build .. use 1461ms.
	processing... /public/libs/jquery-ujs.js ..build .. use 115ms.
	processing... /public/libs/bootstrap/js/bootstrap.js ..build .. use 347ms.
	processing... /public/libs/jquery.caret.js ..build .. use 104ms.
	processing... /public/libs/jquery.atwho.js ..build .. use 189ms.
	processing... /public/libs/markdownit.js ..build .. use 1384ms.
	processing... /public/libs/code-prettify/prettify.js ..build .. use 290ms.
	processing... /public/libs/qrcode.js ..build .. use 337ms.
	processing... /public/javascripts/main.js ..build .. use 8ms.
	processing... /public/javascripts/responsive.js ..build .. use 20ms.
✔ Done. Build time 6417 ms.
 🏁  Compile static assets done. Build time 12356 ms.
assets.json is here:  /mnt/bbs/nodeclub/assets.json
write assets.json done. assets.json: 
{
  "/public/editor.min.js": "/public/editor.min.a91fffc3.min.js",
  "/public/stylesheets/index.min.css": "/public/stylesheets/index.min.cca1fdd9.min.css",
  "/public/index.min.js": "/public/index.min.e061b4f6.min.js"
}
```

这里附上原问题链接
`https://zhuanlan.zhihu.com/p/76946211`
