### ISSUE TITLE
ceotos 安装报错

### ISSUE THREAD

**Issue by andrew7baker** [cnodejs/nodeclub#1116]
node --version
v8.12.0

```
[root@VM-0-15-centos nodeclub-0.3.6]# make test
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 331 packages in 4.248s
found 19 vulnerabilities (6 low, 3 moderate, 9 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
make[1]: Entering directory `/root/github/nodeclub-0.3.6'
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1456:5)
    at Function.Loader.scan (/root/github/nodeclub-0.3.6/node_modules/loader/lib/loader.js:114:18)
    at /root/github/nodeclub-0.3.6/node_modules/loader/lib/loader.js:160:35
    at Array.forEach (<anonymous>)
    at Function.Loader.scanDir (/root/github/nodeclub-0.3.6/node_modules/loader/lib/loader.js:155:9)
    at Object.<anonymous> (/root/github/nodeclub-0.3.6/bin/combo:13:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
make[1]: *** [build] Error 1
make[1]: Leaving directory `/root/github/nodeclub-0.3.6'
make: *** [test] Error 2
```

````
 [root@VM-0-15-centos nodeclub-0.3.6]# node app.js
/root/github/nodeclub-0.3.6/node_modules/mongodb/lib/mongodb/db.js:865
      || (selector['mapreduce'] && selector.out = 'inline')) {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /root/github/nodeclub-0.3.6/node_modules/mongodb/lib/mongodb/index.js:29:17 
```

**Comment by andrew7baker** [comment]
转研究egg-cnode 了
