### ISSUE TITLE
本地搭建

### ISSUE THREAD

**Issue by leekangtaqi** [cnodejs/nodeclub#480]
a神         本地 install没报错
test : should format date 报错了

115 passing (6s)
  1 failing

  1) test/common/tools.test.js should format date:
     AssertionError: expected '1969-12-31 19:00' to match /1970\-01\-01 0\d:00/
    at Assertion.fail (/usr/local/nodeclub-master/node_modules/should/lib/assertion.js:112:17)
    at Assertion.prop.(anonymous function) [as match] (/usr/local/nodeclub-master/node_modules/should/lib/assertion.js:38:14)
    at Context.<anonymous> (/usr/local/nodeclub-master/test/common/tools.test.js:14:42)
    at callFn (/usr/local/nodeclub-master/node_modules/mocha/lib/runnable.js:250:21)
    at Test.Runnable.run (/usr/local/nodeclub-master/node_modules/mocha/lib/runnable.js:243:7)
    at Runner.runTest (/usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:373:10)
    at /usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:451:12
    at next (/usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:298:14)
    at /usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:308:7
    at next (/usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:246:23)
    at Object._onImmediate (/usr/local/nodeclub-master/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
另外注册接收不到邮件是为什么啊？

**Comment by feitian124** [comment]
我也碰到了:
1. 时间报错, 猜测是时区.
2. 注册邮寄收不到:
1. debug 模式不会发邮件.
2. 需要配邮件服务器.
建议直接到 mongodb 里面将注册的用户设为 active 就可以了

**Comment by alsotang** [comment]
如上面所说

第一个问题应该是时区的问题，new Date 最早的日期是 19700101，你那里到 1969 去了。
第二个问题，把自己设成 admin 看看能不能免激活。不用的话就去 mongodb 里面改改。

**Comment by leekangtaqi** [comment]
非常感谢！ a神 f神
时间问题解决了，
可是邮件还是发不出去
config.js里 我设置了 第三方__126__，并且把__debug__设成了__false__

//邮箱配置
mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'leekangtaqi@126.com',
      pass: '40124555r'
    }
  },
还是发不出去。


过了一会报了个错：
You can debug your app with http://localhost:3000
New Relic for Node.js halted startup due to an error:
Error: Unknown license key
  at StreamSink.parser [as callback] (/usr/local/nodeclub-master/node_modules/newrelic/lib/collector/parse-response.js:81:25)
  at StreamSink.end (/usr/local/nodeclub-master/node_modules/newrelic/lib/util/stream-sink.js:43:8)
  at IncomingMessage.onend (_stream_readable.js:502:10)
  at IncomingMessage.g (events.js:180:16)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at /usr/local/nodeclub-master/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
  at process._tickCallback (node.js:442:13)

**Comment by luoyjx** [comment]
你试试把
```
port: 25,
```
那里改成：
```
secureConnection: true,
port: 465,
```
看下能不能行
我才用nodemailer做了示例的
[传送门](http://blog.gaoqixhb.com/p/54e19950f8899e822ec02d52)

**Comment by shixianjun** [comment]
win7下安装报错呀
$ npm install
/
> bcrypt@0.8.1 install d:\gitpro\nodeclub\node_modules\bcrypt
> node-gyp rebuild


d:\gitpro\nodeclub\node_modules\bcrypt>node "d:\Program Files (x86)\nodejs\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (d:\Program Files (x86)\nodejs\node_modules\n
pm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at d:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:93:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "d:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\gitpro\nodeclub\node_modules\bcrypt
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "d:\\Program Files (x86)\\nodejs\\node.exe" "d:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.1 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

什么问题呢

**Comment by shixianjun** [comment]
python 我在cmd下是可以的呀

**Comment by alsotang** [comment]
win7 我搞不定..

**Comment by shaqueoneal** [comment]
121 passing (8s)
  1 failing

  1) test/api/v1/tools.test.js should response with loginname:
     Uncaught Error: Error setting TTL index on collection : sessions
    at /home/share/z07042/MyPrj/nodeclub-master/node_modules/connect-mongo/lib/connect-mongo.js:161:23
    at /home/share/z07042/MyPrj/nodeclub-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1430:36
    at __executeInsertCommand (/home/share/z07042/MyPrj/nodeclub-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/home/share/z07042/MyPrj/nodeclub-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at /home/share/z07042/MyPrj/nodeclub-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1427:14
这个怎么搞？mongo是3.0的

**Comment by alsotang** [comment]
线上是用 2.6 的。

2015-03-13 11:56 GMT+08:00 shaqueoneal <notifications@github.com>:

**Comment by shaqueoneal** [comment]
这个没有卸载脚本吗？ms Makefile 没有 uninstall 也没有clean？这样不好吧？

**Comment by alsotang** [comment]
makefile 里的操作都没有影响到项目文件夹以外。删了文件夹就好了。

2015-03-13 17:51 GMT+08:00 shaqueoneal <notifications@github.com>:

**Comment by Samurais** [comment]
@alsotang 
README里写node是v1.5，从官方网站找不到 https://github.com/joyent/node/tags
请问线上是什么版本？

**Comment by alsotang** [comment]
@Samurais https://iojs.org/en/index.html

**Comment by wy19901227** [comment]
把跑起来的步骤  写的 详细点   谢谢了 ，跑不起来。。。

**Comment by kaixinsoft** [comment]
win7下安装报错呀
$ npm install
/

    bcrypt@0.8.1 install d:\gitpro\nodeclub\node_modules\bcrypt

我也是这个搞不定，bcrypt rebuild的话，好像挺麻烦，失败告终

**Comment by luoyjx** [comment]
要装VS

**Comment by kaixinsoft** [comment]
安装的vs2010，python好像没有装

**Comment by luoyjx** [comment]
python 2.7

**Comment by kaixinsoft** [comment]
C:\Program Files\nodejs>npm install bcrypt --registry=https://registry.npm.taoba
o.org
npm WARN package.json path@0.11.14 path is also the name of a node core module.
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt" "--registry=https://reg
istry.npm.taobao.org"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Program Files\nodejs\node_modules\bcrypt
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, rmdir 'C:\Program Files\nodejs\node_modules\bcrypt'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Program Files\nodejs\node_mo
dules\bcrypt'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, rmdir 'C:\Program Files\nodejs\nod
e_modules\bcrypt']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Program Files\\nodejs\\node_modules\\bc
rypt' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by kaixinsoft** [comment]
C:\Program Files\nodejs>npm install bcrypt
npm WARN package.json path@0.11.14 path is also the name of a node core module.
/
> bcrypt@0.8.2 install C:\Program Files\nodejs\node_modules\bcrypt
> node-gyp rebuild


C:\Program Files\nodejs\node_modules\bcrypt>if not defined npm_config_node_gyp (
node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
  blowfish.cc
  bcrypt.cc
  bcrypt_node.cc
C:\Program Files\nodejs\node_modules\bcrypt\node_modules\nan\nan.h(23): fatal e
rror C1083: 无法打开包括文件:“uv.h”: No such file or directory [C:\Program Fil
es\nodejs
\node_modules\bcrypt\build\bcrypt_lib.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 5.1.2600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

-----------------------------------

bcrypt\build\bcrypt_lib.vcxproj]
文件确实没有

**Comment by alsotang** [comment]
用 windows 玩 node 会遇到很多麻烦，还是考虑用 *nix 吧


2015-04-23 16:23 GMT+08:00 kaixinsoft <notifications@github.com>:

**Comment by kaixinsoft** [comment]
好吧，去linux下折腾一下

**Comment by saleopt** [comment]
这个版本是只有前台，还是前台及后台管理都有？

**Comment by alsotang** [comment]
整套代码都在这里

2015-06-07 10:37 GMT+08:00 saleopt <notifications@github.com>:

**Comment by federerlee** [comment]
I am using node 0.12.6. After fixing some errors, and update the modules there are still problems existing, And I have tried the solutions listed above, but all of them don’t work for my case. I have searched on the google, but cannot find the solution yet. It should be related to the version violate problem. But any other ways to fix them?  BTW, my OS is Ubuntu 14.04 LTS. Thank you in advance!

Error log is following:

/nodeclub/node_modules/bcrypt/node_modules/bindings/bindings.js:83

throw e

^

Error: Module did not self-register.

at Error (native)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at bindings (/home/federer/nodeclub/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)

at Object.<anonymous> (/home/federer/nodeclub/node_modules/bcrypt/bcrypt.js:3:35)

at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous> (/home/federer/nodeclub/common/tools.js:1:76)

at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous> (/home/federer/nodeclub/models/base_model.js:5:13)

at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous> (/home/federer/nodeclub/models/user.js:2:17)

at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous> (/home/federer/nodeclub/models/index.js:14:1)

at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Module.require (module.js:365:17)

at require (module.js:384:17)

at Object.<anonymous> (/home/federer/nodeclub/app.js:22:1)
at Module._compile (module.js:460:26)

at Object.Module._extensions…js (module.js:478:10)

at Module.load (module.js:355:32)

at Function.Module._load (module.js:310:12)

at Function.Module.runMain (module.js:501:10)

at startup (node.js:129:16)

at node.js:814:3



and I change to downgrade to use node v0.10.40. After reinstalling missing modules, node app.js is applicable. And then it runs!
log prints:
Nodeclub listening on port 3000
God bless love…
You can debug your app with http://localhost:3000
When vising http://localhost:3000, the interfaces for Nodeclub shows. But error log again, show blow.
I think it should also be related to version violation problem, but how to fix it? Thank you in advance!

http.js:852

throw new TypeError(‘first argument must be a string or Buffer’);

^

TypeError: first argument must be a string or Buffer

at ServerResponse.OutgoingMessage.write (http.js:852:11)

at ServerResponse.OutgoingMessage.end (http.js:982:16)

at /home/federer/nodeclub/node_modules/loader/lib/loader.js:90:13

at /home/federer/nodeclub/node_modules/less/lib/less/render.js:35:17

at /home/federer/nodeclub/node_modules/less/lib/less/parse.js:63:17

at Object.finish [as _finish] (/home/federer/nodeclub/node_modules/less/lib/less/parser/parser.js:183:28)

at Object.ImportVisitor._onSequencerEmpty (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-visitor.js:35:14)

at ImportSequencer.tryRun (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)

at Object.ImportVisitor.run (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-visitor.js:29:25)

at Object.Parser.parse (/home/federer/nodeclub/node_modules/less/lib/less/parser/parser.js:189:22)

at Object.parse (/home/federer/nodeclub/node_modules/less/lib/less/parse.js:61:18)

at Object.render (/home/federer/nodeclub/node_modules/less/lib/less/render.js:25:18)

at /home/federer/nodeclub/node_modules/loader/lib/loader.js:83:12

at fs.js:272:14

at Object.oncomplete (fs.js:108:15)

**Comment by federerlee** [comment]
and I change to downgrade to use node v0.10.40. After reinstalling missing modules, node app.js is applicable. And then it runs!
log prints:
Nodeclub listening on port 3000
God bless love…
You can debug your app with http://localhost:3000
When vising http://localhost:3000, the interfaces for Nodeclub shows. But error log again, show blow.
I think it should also be related to version violation problem, but how to fix it? Thank you in advance!

http.js:852

throw new TypeError(‘first argument must be a string or Buffer’);

^

TypeError: first argument must be a string or Buffer

at ServerResponse.OutgoingMessage.write (http.js:852:11)

at ServerResponse.OutgoingMessage.end (http.js:982:16)

at /home/federer/nodeclub/node_modules/loader/lib/loader.js:90:13

at /home/federer/nodeclub/node_modules/less/lib/less/render.js:35:17

at /home/federer/nodeclub/node_modules/less/lib/less/parse.js:63:17

at Object.finish [as _finish] (/home/federer/nodeclub/node_modules/less/lib/less/parser/parser.js:183:28)

at Object.ImportVisitor._onSequencerEmpty (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-visitor.js:35:14)

at ImportSequencer.tryRun (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)

at Object.ImportVisitor.run (/home/federer/nodeclub/node_modules/less/lib/less/visitors/import-visitor.js:29:25)

at Object.Parser.parse (/home/federer/nodeclub/node_modules/less/lib/less/parser/parser.js:189:22)

at Object.parse (/home/federer/nodeclub/node_modules/less/lib/less/parse.js:61:18)

at Object.render (/home/federer/nodeclub/node_modules/less/lib/less/render.js:25:18)

at /home/federer/nodeclub/node_modules/loader/lib/loader.js:83:12

at fs.js:272:14

at Object.oncomplete (fs.js:108:15)

**Comment by federerlee** [comment]
when running the command line: make test 
What It listed are just warnings, but no error details for both 0.12.6 and 0.10.40:
make:*** [test] Error 1

**Comment by alsotang** [comment]
@federerlee remove the `node_modules` directory, and re-install all deps.
`bcrypt` is a c++ addon, so it's sensitive with v8 version.

**Comment by federerlee** [comment]
@alsotang Thank you! Your solution works on 0.10.40:
sudo rm node_moduels -r
npm install
...
node app.js
 Then everything seems OK.
NodeClub listening on port 3000
God bless love....
You can debug your app with http://localhost:3000



Started 2015-09-02T06:14:02.497Z GET / 127.0.0.1
  Cache set {"deleted":false}pages 0ms
  MONGO topics.find {"conditions":{"deleted":false,"tab":{"$ne":"job"},"reply_count":0},"options":{"limit":5,"sort":{"create_at":-1},"fields":{}},"collectionName":"topics"} 65ms
  Cache set no_reply_topics 0ms
  MONGO topics.find {"conditions":{"deleted":false},"options":{"skip":0,"limit":20,"sort":{"top":-1,"last_reply_at":-1},"fields":{}},"collectionName":"topics"} 71ms
  MONGO users.find {"conditions":{"is_block":false},"options":{"limit":10,"sort":{"score":-1}},"collectionName":"users"} 74ms
  Cache set tops 0ms
  Render view index (88ms)
Completed 200 (188ms)


Started 2015-09-02T06:14:03.105Z GET /favicon.ico 127.0.0.1
Completed 404 (9ms)
 
And local host can be visited properly!
But the solution doesn't work on 0.12.06 yet. Problems still exist on 0.12.06.
But it confirms that it is a version violation issue.
I will take a look at this in the future by myself.
Thank you for you anwser!

**Comment by alsotang** [comment]
嗯嗯，跑得动就好啦

Er er, run move Jiuhaola -- by google translate

2015-09-02 14:19 GMT+08:00 federerlee <notifications@github.com>:

**Comment by dotku** [comment]
时区问题如何修复呀？！不过是跑起来了... 另外 nodeclub 是基于什么框架的？

**Comment by etoah** [comment]
express
