### ISSUE TITLE
make install报错，貌似bcrypt出问题了

### ISSUE THREAD

**Issue by 03128crz** [cnodejs/nodeclub#505]
npm WARN engine xmlbuilder@2.5.0: wanted: {"node":"0.8.x || 0.10.x || 0.11.x  || 1.0.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-58fd7291: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror http://ikt.pm2.io/ikt.git /root/.npm/_git-remotes/http-ikt-pm2-io-ikt-git-58fd7291: undefined
npm WARN optional dep failed, continuing ikt@git+http://ikt.pm2.io/ikt.git#master
 
> bcrypt@0.8.1 install /storage/app/nodeclub/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: Connection closed while downloading tarball file
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:239:14)
gyp ERR! stack     at Request.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1192:46)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (_http_client.js:240:11)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 2.6.18-371.11.1.el5
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /storage/app/nodeclub/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5
 
> kerberos@0.0.7 install /storage/app/nodeclub/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
> bson@0.2.21 install /storage/app/nodeclub/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> kerberos@0.0.3 install /storage/app/nodeclub/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> bson@0.2.5 install /storage/app/nodeclub/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Linux 2.6.18-371.11.1.el5
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" ""
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/app/nodeclub/npm-debug.log
make: *** [install] Error 1

**Comment by 03128crz** [comment]
原来是python版本低于2.7导致的，设置下版本
 npm config set python /usr/local/python27/bin/python2.7
