### ISSUE TITLE
make test 有一个不通过，是什么原因，请问有影响吗

### ISSUE THREAD

**Issue by 03128crz** [cnodejs/nodeclub#506]
134 passing (8s)
  1 failing

  1) test/common/cache.test.js should expire:
     Uncaught AssertionError: expected { age: 23 } to not exist
    at /storage/app/nodeclub/test/common/cache.test.js:18:22
    at /storage/app/nodeclub/common/cache.js:13:5
    at try_callback (/storage/app/nodeclub/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/storage/app/nodeclub/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/storage/app/nodeclub/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/storage/app/nodeclub/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/storage/app/nodeclub/node_modules/redis/lib/parser/javascript.js:203:22)
    at RedisClient.on_data (/storage/app/nodeclub/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/storage/app/nodeclub/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by alsotang** [comment]
重跑一次试试？

2015-04-05 18:05 GMT+08:00 james <notifications@github.com>:
