### ISSUE TITLE
"Parameter 'url' must be a string, not " + typeof url

### ISSUE THREAD

**Issue by tvvocold** [cnodejs/nodeclub#537]
$node app.js
```
url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
  at Url.parse (url.js:107:11)
  at Object.urlParse [as parse] (url.js:101:5)
  at Object.<anonymous> (/var/lib/openshift/5577aedd4382ec6fc000014d/app-root/runtime/repo/app.js:57:34)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3
```
$ make start
```
Scaned.
[ { target: '/public/stylesheets/index.min.css',
    assets:
     [ '/public/libs/bootstrap/css/bootstrap.css',
       '/public/stylesheets/common.css',
       '/public/stylesheets/style.less',
       '/public/stylesheets/responsive.css',
       '/public/stylesheets/jquery.atwho.css',
       '/public/libs/editor/editor.css',
       '/public/libs/webuploader/webuploader.css',
       '/public/libs/code-prettify/prettify.css',
       '/public/libs/font-awesome/css/font-awesome.css' ],
    min: '/public/stylesheets/index.min.a3f7334b.min.css',
    debug: '/public/stylesheets/index.min.a3f7334b.debug.css' },
  { target: '/public/index.min.js',
    assets:
     [ '/public/libs/jquery-2.1.0.js',
       '/public/libs/lodash.compat.js',
       '/public/libs/jquery-ujs.js',
       '/public/libs/bootstrap/js/bootstrap.js',
       '/public/libs/jquery.caret.js',
       '/public/libs/jquery.atwho.js',
       '/public/libs/markdownit.js',
       '/public/libs/code-prettify/prettify.js',
       '/public/libs/qrcode.js',
       '/public/javascripts/main.js',
       '/public/javascripts/responsive.js' ],
    min: '/public/index.min.88a97726.min.js',
    debug: '/public/index.min.88a97726.debug.js' },
  { target: '/public/editor.min.js',
    assets:
     [ '/public/libs/editor/editor.js',
       '/public/libs/webuploader/webuploader.withoutimage.js',
       '/public/libs/editor/ext.js' ],
    min: '/public/editor.min.ca00fda0.min.js',
    debug: '/public/editor.min.ca00fda0.debug.js' },
  { target: '/public/editor.min.js',
    assets:
     [ '/public/libs/editor/editor.js',
       '/public/libs/webuploader/webuploader.withoutimage.js',
       '/public/libs/editor/ext.js' ],
    min: '/public/editor.min.ca00fda0.min.js',
    debug: '/public/editor.min.ca00fda0.debug.js' },
  { target: '/public/editor.min.js',
    assets:
     [ '/public/libs/editor/editor.js',
       '/public/libs/webuploader/webuploader.withoutimage.js',
       '/public/libs/editor/ext.js' ],
    min: '/public/editor.min.ca00fda0.min.js',
    debug: '/public/editor.min.ca00fda0.debug.js' } ]
Compile static assets done.
assets.json is here: /var/lib/openshift/5577aedd4382ec6fc000014d/app-root/runtime/repo/assets.json
write assets.json done. assets.json:
{"/public/stylesheets/index.min.css":"/public/stylesheets/index.min.a3f7334b.min.css","/public/index.min.js":"/public/index.min.88a97726.min.js","/public/editor
.min.js":"/public/editor.min.ca00fda0.min.js"}
```
求解

**Comment by crishelyumul** [comment]
Solved mine by exporting my app_url.
