### ISSUE TITLE
请教：服务器部署 “Cannot read property 'user' of undefined”

### ISSUE THREAD

**Issue by mittya** [cnodejs/nodeclub#558]
在本地系统部署正常，放到服务器上（Ubuntu 14.04 x64 on DigitalOcean）就出现这个问题了，开始的时候还是正常的，运行了半天就出现了。

原来是自己修改后的版本，后来直接从 nodeclub 上 clone 的也出现了同样的问题。

`config.js` 里的 `session_secret ` 和 `auth_cookie_name ` 已修改。

服务器上配置好最后运行的 `make start`。

在这里请教下是什么问题呢？谢谢！

=

开启 debug 后错误日志：

```bash
Connect
500 TypeError: Cannot read property 'user' of undefined
 at exports.authUser (/root/nodeclub/middlewares/auth.js:94:18)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at Passport.initialize (/root/nodeclub/node_modules/passport/lib/passport/middleware/initialize.js:69:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at session (/root/nodeclub/node_modules/express-session/index.js:145:61)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at compression (/root/nodeclub/node_modules/compression/index.js:217:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at cookieParser (/root/nodeclub/node_modules/cookie-parser/index.js:48:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at methodOverride (/root/nodeclub/node_modules/method-override/index.js:58:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at urlencodedParser (/root/nodeclub/node_modules/body-parser/lib/types/urlencoded.js:72:36)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at jsonParser (/root/nodeclub/node_modules/body-parser/lib/types/json.js:83:36)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at frameguard (/root/nodeclub/node_modules/helmet/node_modules/frameguard/index.js:32:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at responseTime (/root/nodeclub/node_modules/response-time/index.js:69:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/express/lib/router/index.js:191:16
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/express/lib/router/index.js:191:16
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/loader/lib/loader.js:70:14
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at exports.render (/root/nodeclub/middlewares/render.js:16:3)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at module.exports (/root/nodeclub/middlewares/request_log.js:19:3)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at expressInit (/root/nodeclub/node_modules/express/lib/middleware/init.js:23:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at query (/root/nodeclub/node_modules/express/lib/middleware/query.js:28:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at Function.proto.handle (/root/nodeclub/node_modules/express/lib/router/index.js:165:3)
 at Function.app.handle (/root/nodeclub/node_modules/express/lib/application.js:141:10)
 at Server.app (/root/nodeclub/node_modules/express/lib/express.js:28:9)
 at Server.EventEmitter.emit (events.js:98:17)
 at HTTPParser.parser.onIncoming (http.js:2108:12)
 at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
 at Socket.socket.ondata (http.js:1966:22)
 at TCP.onread (net.js:525:27)
 at exports.authUser (/root/nodeclub/middlewares/auth.js:94:18)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at Passport.initialize (/root/nodeclub/node_modules/passport/lib/passport/middleware/initialize.js:69:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at session (/root/nodeclub/node_modules/express-session/index.js:145:61)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at compression (/root/nodeclub/node_modules/compression/index.js:217:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at cookieParser (/root/nodeclub/node_modules/cookie-parser/index.js:48:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at methodOverride (/root/nodeclub/node_modules/method-override/index.js:58:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at urlencodedParser (/root/nodeclub/node_modules/body-parser/lib/types/urlencoded.js:72:36)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at jsonParser (/root/nodeclub/node_modules/body-parser/lib/types/json.js:83:36)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at frameguard (/root/nodeclub/node_modules/helmet/node_modules/frameguard/index.js:32:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at responseTime (/root/nodeclub/node_modules/response-time/index.js:69:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/express/lib/router/index.js:191:16
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/express/lib/router/index.js:191:16
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at /root/nodeclub/node_modules/loader/lib/loader.js:70:14
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at exports.render (/root/nodeclub/middlewares/render.js:16:3)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at module.exports (/root/nodeclub/middlewares/request_log.js:19:3)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at expressInit (/root/nodeclub/node_modules/express/lib/middleware/init.js:23:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at query (/root/nodeclub/node_modules/express/lib/middleware/query.js:28:5)
 at Layer.handle [as handle_request] (/root/nodeclub/node_modules/express/lib/router/layer.js:76:5)
 at trim_prefix (/root/nodeclub/node_modules/express/lib/router/index.js:270:13)
 at /root/nodeclub/node_modules/express/lib/router/index.js:237:9
 at Function.proto.process_params (/root/nodeclub/node_modules/express/lib/router/index.js:312:12)
 at /root/nodeclub/node_modules/express/lib/router/index.js:228:12
 at Function.match_layer (/root/nodeclub/node_modules/express/lib/router/index.js:295:3)
 at next (/root/nodeclub/node_modules/express/lib/router/index.js:189:10)
 at Function.proto.handle (/root/nodeclub/node_modules/express/lib/router/index.js:165:3)
 at Function.app.handle (/root/nodeclub/node_modules/express/lib/application.js:141:10)
 at Server.app (/root/nodeclub/node_modules/express/lib/express.js:28:9)
 at Server.EventEmitter.emit (events.js:98:17)
 at HTTPParser.parser.onIncoming (http.js:2108:12)
 at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
 at Socket.socket.ondata (http.js:1966:22)
 at TCP.onread (net.js:525:27)
```

**Comment by alsotang** [comment]
感觉是没装 redis？

2015-08-20 16:52 GMT+08:00 MY <notifications@github.com>:

**Comment by mittya** [comment]
@alsotang :+1: 非常感谢！

服务器重启了几次，redis 服务没有启动，得弄个自动启动了。

第一次部署 Node 应用，自己还得了解多些东西。
