### ISSUE TITLE
为何邮箱收不到注册激活邮件？

### ISSUE THREAD

**Issue by hehaiquangv** [cnodejs/nodeclub#751]
为何邮箱收不到注册激活邮件？gmail和QQ邮箱都不可以

**Comment by alsotang** [comment]
smtp没配置正确？


2016-02-14 20:06 GMT+08:00 hehaiquangv <notifications@github.com>:

**Comment by nnnbnnn** [comment]
同问，config.js下debug要改成false才能发送邮件吗？改了之后win7下出错
[ERROR] cheese - You must execute `make build` before start app when mini_assets is true.
win7下怎么make build，新手求教。。。。

**Comment by henry4c** [comment]
同问

**Comment by alsotang** [comment]
windows 的问题自己 debug 调一下吧。

linux 下面的话，如果 config.js 里面的 debug 是 false，并且 smtp
设置正确的话，应该是发得出的啊。以及，我印象中有一段时间网易邮箱是不给 smtp 权限的，QQ 邮箱就没这种限制。还是一步步 debug 试试吧。

2016-02-17 14:36 GMT+08:00 henry4c <notifications@github.com>:

**Comment by benliu723** [comment]
如果是测试的话，直接去mongodb的数据库，将 users 表的 active 字段设为 true 即可，如果发布到线上，则需要 按照 alsotang的评论来进行设置。

**Comment by nnnbnnn** [comment]
用MongoVUE直接改数据库是可以，后来通过在win7下安装docker，成功make build，邮件也成功发出！
谢谢！
但是还有关于mongodb容器读取win7数据文件出错，还请大神指点！https://cnodejs.org/topic/56c951a9d1e0945c614187fc

**Comment by jadeball** [comment]
@alsotang 为什么我debuger模式启动 报告如下错误，导致没发调试啊：
/usr/local/bin/node --debug-brk=50988 --nolazy app.js
Debugger listening on port 50988
/work/Bitbucket/antdream/nodeclub/node_modules/log4js/lib/appenders/console.js:3
, consoleLog = console.log.bind(console);
                          ^

TypeError: Cannot read property 'bind' of undefined
  at Object.<anonymous> (/work/Bitbucket/antdream/nodeclub/node_modules/log4js/lib/appenders/console.js:3:27)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/work/Bitbucket/antdream/nodeclub/node_modules/log4js/lib/log4js.js:67:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/work/Bitbucket/antdream/nodeclub/common/logger.js:6:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/work/Bitbucket/antdream/nodeclub/middlewares/mongoose_log.js:2:16)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/work/Bitbucket/antdream/nodeclub/app.js:22:1)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at [object Object].Module.runMain [as _onTimeout] (module.js:441:10)
  at Timer.listOnTimeout (timers.js:92:15)


Process finished with exit code 1

而正常启动 非debuger模式 则没问题

**Comment by mqliang** [comment]
为什么debug要false才能发邮件？是debug模式故意禁掉了邮件功能吗
