### ISSUE TITLE
当config里面的debug配置成false之后，make build报错

### ISSUE THREAD

**Issue by IvesXiao** [cnodejs/nodeclub#826]
@Elvi ➜  nodeclub git:(master) ✗ make build
/Users/elvis/code/nodeclub/node_modules/loader-builder/lib/builder.js:131
      item.min = `${dirname}/${basename}.${hashed}${extname}`;
                 ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/elvis/code/nodeclub/node_modules/loader-builder/bin/builder:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
make: *** [build] Error 1

**Comment by XGHeaven** [comment]
请升级 node 版本。

**Comment by liygheart** [comment]
clone一下代码 ，make test，日志
```
root@110513:/home/github/nodeclub# make test
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional dep failed, continuing fsevents@1.0.12
Killed
make: *** [install] Error 137
```

**Comment by shawnxiao94** [comment]
[root@iZuf6emvef6hl5tlnsyupxZ nodeclub]# ls
api               bin        controllers  logs         models        package.json       public     views
api_router_v1.js  common     History.md   Makefile     node_modules  package-lock.json  README.md  web_router.js
app.js            config.js  LICENSE      middlewares  oneapm.js     proxy              test
[root@iZuf6emvef6hl5tlnsyupxZ nodeclub]# make build
make: ./node_modules/loader-builder/bin/builder: Command not found
make: *** [Makefile:50: build] Error 127
[root@iZuf6emvef6hl5tlnsyupxZ nodeclub]# node -v
v10.24.0
[root@iZuf6emvef6hl5tlnsyupxZ nodeclub]# npm -v
6.14.11
[root@iZuf6emvef6hl5tlnsyupxZ nodeclub]# 

这个啥错误，折腾了好久
