### ISSUE TITLE
把debug改成false,运行就会报错,提示要make build

### ISSUE THREAD

**Issue by will-min** [cnodejs/nodeclub#834]
如题,node app.js 报错
[2016-04-22 17:46:29.988] [ERROR] cheese - You must execute `make build` before start app when mini_assets is true.
/home/wlm/workspace/sixshot-bbs/app.js:56
    throw e;
    ^

Error: Cannot find module './assets.json'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/home/wlm/workspace/sixshot-bbs/app.js:53:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

提示make build
make build却提示权限不够:

make: execvp: ./node_modules/loader-builder/bin/builder: 权限不够
make: *** [build] 错误 127

**Comment by NetLogoclub** [comment]
我都是cd 到目录下，然后make的

**Comment by will-min** [comment]
@NetLogoclub 肯定都是cd到目录下

**Comment by JacksonTian** [comment]
自己检查下权限

**Comment by NetLogoclub** [comment]
对，文件有没有操作权限，昨天我在本机配好了，放服务器不行，我火起来把mongo 和redis清空了一下，好像配置也有次数限制？
