### ISSUE TITLE
问一下配置的问题

### ISSUE THREAD

**Issue by tianshaokai** [cnodejs/nodeclub#841]
mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'club@126.com',
      pass: 'club'
    }
  },

我需要把 club@126.com  替换为自己的 126 邮箱帐号吗, 

 qn_access: {
    accessKey: 'your access key',
    secretKey: 'your secret key',
    bucket: 'your bucket name',
    origin: 'http://your qiniu domain',
    // 如果vps在国外，请使用 http://up.qiniug.com/ ，这是七牛的国际节点
    // 如果在国内，此项请留空
    uploadURL: 'http://xxxxxxxx',
  },

origin: 'http://your qiniu domain', 这句话是 配置什么的呢？  
 uploadURL: 'http://xxxxxxxx', 我的网站 都在国内 这项 为  ''   就行 了吧

**Comment by tianshaokai** [comment]
@alsotang 看看我的问题吧

**Comment by TakWolf** [comment]
1. 我需要把 club@126.com 替换为自己的 126 邮箱帐号吗?
是的，否则邮件系统不能正常工作，这个涉及到用户注册后的邮件验证。不一定非要126，其他邮件服务商也可以，只要正确配置端口和密码。

2.七牛部分：
origin是你在七牛的空间子域名，可能格式为例如：7xqqqg.dl1.z0.glb.clouddn.com，去你的七牛后台查看

uploadURL是七牛上传接口的API地址，因为你在国外，请配置为 http://up.qiniug.com/

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/14973828/98927ad8-111f-11e6-8de0-d050617727e7.png)
@TakWolf  这是我配置的邮箱  怎么一直发送不出去啊，哪里错 了啊

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/14973863/1a97e022-1120-11e6-884d-f4b40bff7c47.png)

配置貌似是正确的，检查一下 config.js 中让 debug = false，调试状态是不会发送邮件的
如果希望在调试环境下测试，直接修改数据库users表中的active = true

**Comment by tianshaokai** [comment]
谢谢啦

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/14974018/3ec173e4-1122-11e6-83a5-b2743187f0a3.png)
设置为false 后 发现 网页拒绝访问了
是不是我缺少其他服务

**Comment by TakWolf** [comment]
拒绝访问，返回403吗？
调试状态除了邮件之外，其他都正常吗？

如果调试状态都正常，应该不缺服务

**Comment by tianshaokai** [comment]
调试状态网页也能访问， 就是不能发送邮件 无法登录， 改为true 后，网页什么都不返回

**Comment by tianshaokai** [comment]
[2016-05-03 11:30:51.460] [ERROR] cheese - You must execute `make build` before start app when mini_assets is true.
/data/nodejs/nodeclub/app.js:56
    throw e;
    ^

Error: Cannot find module './assets.json'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/data/nodejs/nodeclub/app.js:53:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
看了一下日志 好像是哪里错了

**Comment by TakWolf** [comment]
重新 mark build 一下

**Comment by tianshaokai** [comment]
不好意思啊我对nodejs 不是很熟 不知道如何 mark build  你的意思是重新安装 一下 依赖包吗

**Comment by TakWolf** [comment]
看这里 https://github.com/cnodejs/nodeclub/blob/master/Makefile，这里封装了一些执行命令
mark build 实际执行的是这个命令 https://github.com/cnodejs/nodeclub/blob/master/Makefile#L40

系统环境中确保有mark命令就行，cd 到项目根目录下面，执行命令 mark build

**Comment by alsotang** [comment]
make build。看 makefile 那里，debug 为 true 的时候，静态资源需要编译一下的。

2016-05-03 11:46 GMT+08:00 田绍凯 <notifications@github.com>:

**Comment by alsotang** [comment]
是 make 不是 mark。。。

2016-05-03 11:50 GMT+08:00 TakWolf <notifications@github.com>:

**Comment by TakWolf** [comment]
笔误，我的错

**Comment by tianshaokai** [comment]
@alsotang @TakWolf  感谢你们的帮助 终于可以访问了，我再试试 邮件 能不能发送成功

**Comment by tianshaokai** [comment]
邮件还是无法发送  是不是 yeah.net  邮箱不能呢

**Comment by tianshaokai** [comment]
session_secret: 'node_club_secret', // 务必修改 这里需要修改为什么呢 我这个好像没有改

**Comment by TakWolf** [comment]
邮箱设置中查看一下，看看是否启用了  “POP3/SMTP服务”

session_secret 应该是一个秘药串，用来加密敏感值的，改一下会比较安全

**Comment by tianshaokai** [comment]
已经开启了 还是不行啊 @TakWolf  @alsotang  哪里有问题呢

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/14975669/9c82deb4-1136-11e6-896e-23fe5b6173d2.png)
报了这个错误是 端口不通吗

**Comment by alsotang** [comment]
拿错误代码去google

2016-05-03 13:55 GMT+08:00 田绍凯 <notifications@github.com>:

**Comment by TakWolf** [comment]
目测是密码不对

这个错误我看到过好多次了，凡是部署网易邮箱的，貌似都要折腾一遍这个错误

**Comment by tianshaokai** [comment]
@alsotang 我查了一下没找到什么答案   网上都是这样一句话 提示的错误说的是SMTP服务器返回了一个提示,当TLS激活的时候（你用了SslServer），你给的某个Command命令是不能执行的，  感觉是我服务器配置有问题，我需要安装什么东西呢

**Comment by tianshaokai** [comment]
@alsotang  看网上说的资料 安装了几个 库 发现还是不行，能说说具体的解决方案吗？？

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/15012289/16e35122-122a-11e6-9da6-69486f708199.png)
@alsotang  帮忙解决一下这问题吧，没找到资料啊

**Comment by TakWolf** [comment]
你研究一下看看网易邮箱是不是有授权码这个概念，不是密码

**Comment by TakWolf** [comment]
https://cnodejs.org/topic/56fbfb248a612c5559d16a72

**Comment by tianshaokai** [comment]
@TakWolf  你知道有什么办法解决这个问题吗，我找了好几天也没找到问题原因啊 @alsotang  你知道什么原因吗，希望给出一个解决方案

**Comment by tianshaokai** [comment]
host: "smtp.163.com", // 主机
  secureConnection: true, // 使用 SSL
  port: 465, // SMTP 端口
  auth: {
    user: "xxxxxxxx@163.com", // 账号
    pass: "xxxxxxxx" // 授权密码 而不是邮箱密码
  }

已经可以了

**Comment by tianshaokai** [comment]
@TakWolf @alsotang 我上传的图片到七牛云后，图片无法查看 怎么回事啊，七牛云上的文件还没有文件名称

**Comment by XGHeaven** [comment]
七牛问题请尝试按照这样解决一下试试 #835

**Comment by tianshaokai** [comment]
@TakWolf  你好 七牛上传文件的程序在哪个文件啊，上传时想设置文件名称
