### ISSUE TITLE
启动 nodeclub 总是报错 求各位帮帮忙~~ 谢谢

### ISSUE THREAD

**Issue by Hugh-Wang** [cnodejs/nodeclub#851]
TypeError: OAuth2Strategy requires a clientID option
  at Strategy.OAuth2Strategy (/home/yunfei/kingdom/nodeclub/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:82:34)
  at new Strategy (/home/yunfei/kingdom/nodeclub/node_modules/passport-github/lib/strategy.js:62:18)
  at Object.<anonymous> (/home/yunfei/kingdom/nodeclub/app.js:115:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

**Comment by matthewgao** [comment]
你注释了，config.js的GITHUB配置那部分
