### ISSUE TITLE
请教一下服务器上安装的问题，没看到报什么错，却访问不了

### ISSUE THREAD

**Issue by patrickouc** [cnodejs/nodeclub#881]
我的配置文件config文件
 // mongodb 配置
  db: 'mongodb://45.79.109.190/node_club_dev',

if (process.env.NODE_ENV === 'test') {
  config.db = 'mongodb://45.79.109.190/node_club_test';
}
redis 的配置
![image](https://cloud.githubusercontent.com/assets/4326820/18607712/a554da78-7d07-11e6-9dcf-e3e01539d6e5.png)

服务器上这里redis 跟mongo的地址都写127.0.0.1 是吗
![image](https://cloud.githubusercontent.com/assets/4326820/18607713/b783786c-7d07-11e6-8e28-439258487fc7.png)
mongo里面看到有两个数据库node_club_dev跟node_club_test'

**Comment by patrickouc** [comment]
host 写的是IP 45.79.109.190

**Comment by TakWolf** [comment]
mongo里面看到有两个数据库说明连接是正确的

访问不了指的是什么？是指外网无法浏览吗？

跑测试可以通过吗？

用命令 make start 来运行，见https://github.com/cnodejs/nodeclub/blob/master/Makefile#L46

**Comment by patrickouc** [comment]
刚跑测试试了下，报错了 ，第一次好像没报错，我改了配置就报错了。 是的，我想外网访问。
root@ubuntu:~/project/nodeclub# make start
npm WARN package.json passport@0.3.2 No README data
npm WARN package.json oneapm@1.2.20 No repository field.

/root/project/nodeclub/node_modules/loader-builder/lib/builder.js:131
      item.min = `${dirname}/${basename}.${hashed}${extname}`;
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/project/nodeclub/node_modules/loader-builder/bin/builder:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: *** [build] Error 8

**Comment by TakWolf** [comment]
配置中的debug需要设置为true
这个时候有一部分静态资源需要编译一下

**Comment by patrickouc** [comment]
对的， 是true, 默认好像就是true

**Comment by patrickouc** [comment]
你是说错误是没有编译静态资源是吗？

**Comment by TakWolf** [comment]
我刚才写错了，应该改成Debug=false

我不知道是不是静态资源的问题，你试一下

你的错误指向这里：
`/root/project/nodeclub/node_modules/loader-builder/lib/builder.js:131`

而build命令：
https://github.com/cnodejs/nodeclub/blob/master/Makefile#L40

`@./node_modules/loader-builder/bin/builder views .`

所以感觉是这个问题

**Comment by patrickouc** [comment]
You must execute `make build` before start app when mini_assets is true.

/root/project/nodeclub/app.js:56
    throw e;
          ^
Error: Cannot find module './assets.json'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/project/nodeclub/app.js:53:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3

root@ubuntu:~/project/nodeclub# make build

/root/project/nodeclub/node_modules/loader-builder/lib/builder.js:131
      item.min = `${dirname}/${basename}.${hashed}${extname}`;
                 ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/project/nodeclub/node_modules/loader-builder/bin/builder:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
make: *** [build] Error 8

从报错上看 好像是目录问题一样， 这个随便放哪里都可以把，最后node app.js就好吧

**Comment by TakWolf** [comment]
对的

**Comment by patrickouc** [comment]
我执行make build 之后报的错，你知道什么意思吗
