### ISSUE TITLE
debug设成了false后 跑make test的问题

### ISSUE THREAD

**Issue by KMPYD** [cnodejs/nodeclub#887]
debug设成了false后就不能访问了

**Comment by KMPYD** [comment]
root@163.44.148.79's password: 
[root@host-163-44-148-79 ~]# cd nodeclub
[root@host-163-44-148-79 nodeclub]# # make test
[root@host-163-44-148-79 nodeclub]# make test
[2016-10-02 21:12:23.301] [ERROR] cheese - You must execute `make build` before start app when mini_assets is true.
/root/nodeclub/app.js:56
    throw e;
    ^

Error: Cannot find module './assets.json'
  at Function.Module._resolveFilename (module.js:325:15)
  at Function.Module._load (module.js:276:25)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/root/nodeclub/app.js:53:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/root/nodeclub/test/app.test.js:2:11)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at /root/nodeclub/node_modules/mocha/lib/mocha.js:219:27
  at Array.forEach (native)
  at Mocha.loadFiles (/root/nodeclub/node_modules/mocha/lib/mocha.js:216:14)
  at Mocha.run (/root/nodeclub/node_modules/mocha/lib/mocha.js:468:10)
  at Object.<anonymous> (/root/nodeclub/node_modules/mocha/bin/_mocha:403:18)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:974:3

make: *** [test] 错误 1
[root@host-163-44-148-79 nodeclub]#

**Comment by TakWolf** [comment]
非调试状态需要先运行 `make build` 编译静态文件

**Comment by KMPYD** [comment]
这样设置的：
var config = {
  // debug 为 true 时，用于本地调试
  debug: false,

debug改回true后能访问不能收邮件
因为收不到邮件，注册的用户登录不上去，管理进不了
求解决

**Comment by TakWolf** [comment]
本地调试状态不会发送邮件，调试状态测试用户注册，直接修改数据库字段

**Comment by KMPYD** [comment]
make build
是直接这样输入运行就可以吗

**Comment by TakWolf** [comment]
对

**Comment by KMPYD** [comment]
可以访问了，就是提示错误65
我先把邮件调通

**Comment by KMPYD** [comment]
请问github 登录怎么配置

**Comment by KMPYD** [comment]
本地调试状态不会发送邮件，调试状态测试用户注册，直接修改数据库字段

将 users 表的 active 字段设为 true

还有其他方法进后台吗，我不会改数据库

**Comment by KMPYD** [comment]
可以收到邮件了

**Comment by TakWolf** [comment]
在你的github设置中，创建一个应用，然后在nodeclub配置中，填写回调地址

**Comment by TakWolf** [comment]
mongo客户端，可以试试 https://robomongo.org

**Comment by TakWolf** [comment]
如果问题解决了，记得关闭

**Comment by KMPYD** [comment]
在你的github设置中，创建一个应用，然后在nodeclub配置中，填写回调地址

回调地址怎么写

**Comment by KMPYD** [comment]
我申请了应用，那两串字符填写上去，按照你开始给我的代码编译了之后打开不了

**Comment by TakWolf** [comment]
https://github.com/cnodejs/nodeclub/blob/master/config.default.js#L83

首先配置这里的 clientID    clientSecret

然后把回调地址，也就是 `http://cnodejs.org/auth/github/callback` 填写到你的github设置中

**Comment by KMPYD** [comment]
我申请的是：
Client ID
44cad0f12d99d7a70013
Client Secret
c69da7749173b85f3c639668a90d9fcd71a4295a
我这里配置；
  // github 登陆的配置
  GITHUB_OAUTH: {
    clientID: '44cad0f12d99d7a70013',
    clientSecret: 'c69da7749173b85f3c639668a90d9fcd71a4295a',
    callbackURL: 'http://cnodejs.org/auth/github/callback'

github：配置
homepage url
和authorizaton callback url
这两个位置输入：
http://cnodejs.org/auth/github/callback

是这样的吗

**Comment by TakWolf** [comment]
不要把id贴出来啊，这样不就泄露了吗！调通之后在重新申请一个吧！

github设置：
homepage url ：你的域名
authorizaton callback url ：你的域名/auth/github/callback

**Comment by KMPYD** [comment]
好的，谢谢

**Comment by KMPYD** [comment]
session_secret: 'node_club_secret', // 务必修改
  auth_cookie_name: 'node_club',

这个位置怎么改

**Comment by TakWolf** [comment]
这个是cookie名跟加密秘钥，随便写
