### ISSUE TITLE
make test 出错，commander 模块没安装上， 无法运行

### ISSUE THREAD

**Issue by pangguoming** [cnodejs/nodeclub#900]
CentOS 6.7   make test 出错，commander 模块没安装上，但make install 只有警告。

module.js:327
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/nodeclub/node_modules/mocha/bin/_mocha:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
make: *** [test] Error 1

**Comment by pangguoming** [comment]
https://registry.npmjs.org/macha
下载不了 mocha 模块
