### ISSUE TITLE
回帖自动发邮件提醒功能

### ISSUE THREAD

**Issue by luren5** [cnodejs/nodeclub#919]
准备在源码的基础上添加一个 回帖自动发提醒邮件的功能，但是发现源码 model/user.js 里面有一个字段 receive_reply_mail: {type: Boolean, default: false }， 但是又没找到 receive_reply_mail 在哪个地方有用到？请问是否已经有 回帖自动发提醒邮件的功能 了？

**Comment by shaohao2014** [comment]
请教邮件配置问题，这是我的配置：
debug: false,
mail_opts: {
    host: 'smtp.163.com',
    secureConnection: true,
    port: 465,
    auth: {
      user: 'XXX@163.com',
      pass: 'XXX'
    }
  },
邮件依然无法收到。麻烦了

**Comment by tsuibin** [comment]
debug: false,

mail_opts: {
    host: 'smtp.126.com',
    secureConnection: true,
    port: 465,
    auth: {
      user: 'xxxx@126.com',
      pass: 'xxxx'
    },
    ignoreTLS: false,
  },

无法收到邮件

> send mail finally error { Error: Greeting never received
  at SMTPConnection._formatError (/root/cnode/nodeclub/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:466:15)
  at SMTPConnection._onError (/root/cnode/nodeclub/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:452:16)
  at SMTPConnection.<anonymous> (/root/cnode/nodeclub/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/lib/smtp-connection.js:393:18)
  at ontimeout (timers.js:365:14)
  at tryOnTimeout (timers.js:237:5)
  at Timer.listOnTimeout (timers.js:207:5)
 code: 'ETIMEDOUT' } { from: 'xxxx<xxxx@126.com>',

**Comment by TakWolf** [comment]
@tsuibin 465 是TLS端口，ignoreTLS: true 试一下

**Comment by tsuibin** [comment]
debug: false,
 mail_opts: {
    host: 'smtp.126.com',
    secureConnection: true,
    port: 465,
    auth: {
      user: 'xxxx@126.com',
      pass: 'xxxx' //这个是使用的授权码
    },
    ignoreTLS: true,
  },

这个设置可以发送邮件了

**Comment by hefeng1208** [comment]
没报错 ！但是邮箱里面没有！就是收不到邮件
mail_opts: {
    host: 'smtp.126.com',
    port: 25,
    auth: {
      user: 'sssss@163.com',
      pass: 'XXXX'  //  授权码
    },
    ignoreTLS: true,
  },

**Comment by TakWolf** [comment]
https://github.com/cnodejs/nodeclub/issues/854

邮件问题，试试这个
