### ISSUE TITLE
启动提示  Invalid left-hand side in assignment   新手求帮忙

### ISSUE THREAD

**Issue by yinxulai** [cnodejs/nodeclub#933]
\nodeclub\node_modules\.1.1.2@mongodb\lib\mongodb\db.js:865
      || (selector['mapreduce'] && selector.out = 'inline')) {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\hiibook\Desktop\nodeclub\node_modules\.1.1.2@mongodb\lib\mongodb\index.js:29:17
    at Array.forEach (native)

不知是配置问题还是什么问题，求告知
close

**Comment by qq76319973** [comment]
我也出现这个问题，能告诉我怎么解决的吗？
