### ISSUE TITLE
很严重的两个问题，1.为什么我按标准流程部署的nodeclub，刚开放使用一周，所有的数据都丢失了？2.并且启动在后台的nodeclub进程会莫名其妙的消失，进程消失的情况出现了好几次！

### ISSUE THREAD

**Issue by jiyidly** [cnodejs/nodeclub#969]
很严重的两个问题，1.为什么我按标准流程部署的nodeclub，刚开放使用一周，所有的数据都丢失了？2.并且启动在后台的nodeclub进程会莫名其妙的消失，进程消失的情况出现了好几次！

**Comment by TakWolf** [comment]
使用中，没遇到问题，无法解答。请提供详细的环境和日志信息。

请确定：
1. config.debug = false

2.检查mongo的使用，确定不是手动还原

3.监控服务器内存情况，确认是否为内存不足

**Comment by awong1900** [comment]
多做些测试， 你看论坛运行这么久了也没事。

**Comment by tomoya92** [comment]
我觉得应该是自己误删了mongodb的数据库

**Comment by jiyidly** [comment]
确认是没有人动mongodb，确认config.debug = false，您说的手动还原是在哪里？
内存情况我们正在查，这个问题确实很伤。。。

**Comment by jiyidly** [comment]
logs目录下，只有一个日志文件，内容只有
[2017-06-28 11:22:16.731] [ERROR] cheese - connect to mongodb://127.0.0.1/node_club_dev error:  connect ECONNREFUSED 127.0.0.1:27017
[2017-06-29 10:53:00.781] [ERROR] cheese - { ForbiddenError: invalid csrf token
  at verifytoken (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/csurf/index.js:269:11)
  at csrf (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/csurf/index.js:97:7)
  at /root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/app.js:126:14
  at Layer.handle [as handle_request] (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/express/lib/router/index.js:317:13)
  at /root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/express/lib/router/index.js:284:7
  at Function.process_params (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/express/lib/router/index.js:335:12)
  at next (/root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/node_modules/express/lib/router/index.js:275:10)
  at /root/deploy/xiniuedu/trunk/server/main/thirdparty/nodeclub/nodeclub/nodeclub/middlewares/auth.js:43:5

**Comment by ideaplat** [comment]
我的数据也全部丢失

**Comment by awong1900** [comment]
打脸了。 我的数据也丢失了。百度有4000多的索引量。 怎么找回，大家有方法吗？ bbs.zuqiuxunlian.com

阿里云确实报过一次内存不足的错误：
![image](https://user-images.githubusercontent.com/4022612/72737127-ebe7cb00-3bd9-11ea-996a-2fa0febc4d49.png)
那内存不足会把数据库清掉吗？

**Comment by houyushan** [comment]
mongodb数据库设置是否有问题，不要设置成所有人都可访问，会被别人删除。
